const ConfigAddressConfig = 0;
const MinterAddressConfig = 2;
const BlackholeAddressConfig = 5;
const ExtraCurrencyAuthorizationConfig = -0xEC;

const OP_MINT = 0x100d888c;
const OP_MINT_REGISTERED = 0x82a325a4;
const OP_ECHO = 0xffd7ce8b;
const OP_ECHOED = 0x94dbbb05;
const OP_MINTED = 0x442526bd;


const ERROR_NO_PARAM_6 = 1006;
const ERROR_UNAUTHORIZED_MINT_REQUEST = 1008;
const ERROR_UNCOVERED_FEE = 1009;
const ERROR_UNKNOWN_OP = 10010;
const ERROR_NO_AUTH_CONFIG = 10011;


const MY_WORKCHAIN = -1;
const ONECOIN = 1000000000;

