const ConfigContractConfig = 0;
const MinterAddressConfig = 2;
const BlackholeAddressConfig = 5;
const ExtraCurrencyAuthorizationConfig = -0xEC;

const OP_MINT = 0x1674b0a0;
const OP_MINT_REGISTERED = 0xb0a01675;
const OP_ECHO = 0x10;
const OP_ECHOED = 0x11;
const OP_MINTED = 0x12;


const ERROR_NO_PARAM_6 = 1006;
const ERROR_UNAUTHORIZED_MINT_REQUEST = 1008;
const ERROR_UNCOVERED_FEE = 1009;
const ERROR_UNKNOWN_OP = 10010;


const MY_WORKCHAIN = -1;
const ONECOIN = 1000000000;

